DROP TRIGGER IF EXISTS trg_projects_workspace ON projects;
DROP TRIGGER IF EXISTS trg_checklist_groups_workspace ON checklist_groups;
DROP TRIGGER IF EXISTS trg_tags_workspace ON tags;
DROP TRIGGER IF EXISTS trg_tasks_workspace ON tasks;
DROP TRIGGER IF EXISTS trg_blockers_workspace ON blockers;
DROP TRIGGER IF EXISTS trg_task_tags_workspace ON task_tags;
DROP TRIGGER IF EXISTS trg_sync_operations_workspace ON sync_operations;
DROP TRIGGER IF EXISTS trg_sync_changes_workspace ON sync_changes;
DROP FUNCTION IF EXISTS fill_personal_workspace_id();
ALTER TABLE sync_operations DROP CONSTRAINT IF EXISTS sync_operations_pkey;
ALTER TABLE sync_operations ADD PRIMARY KEY (user_id, operation_id);
ALTER TABLE task_tags DROP CONSTRAINT IF EXISTS task_tags_pkey;
ALTER TABLE task_tags ADD PRIMARY KEY (user_id, task_id, tag_id);
DROP INDEX IF EXISTS idx_sync_changes_workspace_cursor;
DROP INDEX IF EXISTS idx_sync_operations_workspace;
DROP INDEX IF EXISTS idx_task_tags_workspace;
DROP INDEX IF EXISTS idx_blockers_workspace_task;
DROP INDEX IF EXISTS idx_tasks_workspace_parent_sort;
DROP INDEX IF EXISTS idx_tasks_workspace_updated;
DROP INDEX IF EXISTS idx_tags_workspace_name;
DROP INDEX IF EXISTS idx_checklist_groups_workspace;
DROP INDEX IF EXISTS idx_projects_workspace;
ALTER TABLE sync_changes DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE sync_operations DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE task_tags DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE blockers DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE tasks DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE tags DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE checklist_groups DROP COLUMN IF EXISTS workspace_id;
ALTER TABLE projects DROP COLUMN IF EXISTS workspace_id;
DELETE FROM schema_metadata WHERE key = 'workspace_sync_model';
